#ifndef  __TASK_MSG_H__
#define  __TASK_MSG_H__



typedef enum
{
    TASK_MSG_ADC_COMPLETE,
    TASK_MSG_REQ_NET_WEIGHT,
    TASK_MSG_REQ_CALIBRATE_ZERO,
    TASK_MSG_REQ_CALIBRATE_FULL,
    TASK_MSG_REQ_CALIBRATE_ZERO_VALUE,
    TASK_MSG_REQ_CALIBRATE_FULL_VALUE,
    TASK_MSG_REQ_REMOVE_TAR_WEIGHT,
    TASK_MSG_REQ_SET_ADDR,
    TASK_MSG_REQ_SENSOR_ID,
    TASK_MSG_REQ_FW_VERSION,
    TASK_MSG_REQ_ADDR,
    TASK_MSG_REQ_DIR,
    TASK_MSG_RSP_ADC_COMPLETE,
    TASK_MSG_RSP_NET_WEIGHT,
    TASK_MSG_RSP_CALIBRATE_ZERO,
    TASK_MSG_RSP_CALIBRATE_FULL,
    TASK_MSG_RSP_CALIBRATE_ZERO_VALUE,
    TASK_MSG_RSP_CALIBRATE_FULL_VALUE,
    TASK_MSG_RSP_REMOVE_TAR_WEIGHT,
    TASK_MSG_RSP_SET_ADDR,
    TASK_MSG_RSP_SENSOR_ID,
    TASK_MSG_RSP_FW_VERSION,
    TASK_MSG_RSP_ADDR,
    TASK_MSG_RSP_DIR
}message_type_t;


typedef struct
{
uint32_t   type:8;
uint32_t   value:24;
}task_message_t;



















#endif