/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v5.0
processor: LPC824
package_id: LPC824M201JDH20
mcu_data: ksdk2_0
processor_version: 5.0.0
pin_labels:
- {pin_num: '1', pin_signal: PIO0_23/ADC_3/ACMP_I4, label: LED, identifier: LED_CTRL;LED}
- {pin_num: '2', pin_signal: PIO0_17/ADC_9, label: RWE_485, identifier: RWE_485_CTRL}
- {pin_num: '3', pin_signal: PIO0_13/ADC_10, label: DEBUG_RX}
- {pin_num: '20', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: DEBUG_TX}
- {pin_num: '4', pin_signal: PIO0_12, label: AD_SPI_DO, identifier: AD_SPI_DO}
- {pin_num: '6', pin_signal: PIO0_4/ADC_11, label: TX_232}
- {pin_num: '19', pin_signal: PIO0_0/ACMP_I1, label: RX_232}
- {pin_num: '12', pin_signal: PIO0_1/ACMP_I2/CLKIN, label: AD_SYNC, identifier: AD_SYNC_CTRL}
- {pin_num: '11', pin_signal: PIO0_15, label: AD_SPI_CS, identifier: AD_SPI_CS}
- {pin_num: '13', pin_signal: PIO0_9/XTALOUT, label: EEPROM_SDA}
- {pin_num: '14', pin_signal: PIO0_8/XTALIN, label: EEPROM_SCL}
- {pin_num: '9', pin_signal: PIO0_11/I2C0_SDA, label: DOUT, identifier: DOUT}
- {pin_num: '10', pin_signal: PIO0_10/I2C0_SCL, label: CLK, identifier: CLK}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: USART0, signal: RXD, pin_signal: PIO0_13/ADC_10}
  - {pin_num: '20', peripheral: USART0, signal: TXD, pin_signal: PIO0_14/ACMP_I3/ADC_2}
  - {pin_num: '19', peripheral: USART1, signal: RXD, pin_signal: PIO0_0/ACMP_I1}
  - {pin_num: '6', peripheral: USART1, signal: TXD, pin_signal: PIO0_4/ADC_11}
  - {pin_num: '8', peripheral: SWD, signal: SWDIO, pin_signal: SWDIO/PIO0_2}
  - {pin_num: '7', peripheral: SWD, signal: SWCLK, pin_signal: SWCLK/PIO0_3}
  - {pin_num: '1', peripheral: GPIO, signal: 'PIO0, 23', pin_signal: PIO0_23/ADC_3/ACMP_I4, identifier: LED, direction: OUTPUT, gpio_init_state: 'false'}
  - {pin_num: '9', peripheral: GPIO, signal: 'PIO0, 11', pin_signal: PIO0_11/I2C0_SDA, direction: INPUT}
  - {pin_num: '10', peripheral: GPIO, signal: 'PIO0, 10', pin_signal: PIO0_10/I2C0_SCL, direction: OUTPUT, gpio_init_state: 'false'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for switch matrix.: Enable. */
    CLOCK_EnableClock(kCLOCK_Swm);

    GPIO->CLR[0] = ((GPIO->CLR[0] &
                     /* Mask bits to zero which are setting */
                     (~(GPIO_CLR_CLRP_MASK)))

                    /* Clear output bits (bit 0 = PIOn_0, bit 1 = PIOn_1, etc.). Supported pins depends on the specific
                     * device and package. 0 = No operation. 1 = Clear output bit.: 0x800400u */
                    | GPIO_CLR_CLRP(0x800400u));

    GPIO->DIR[0] = ((GPIO->DIR[0] &
                     /* Mask bits to zero which are setting */
                     (~(GPIO_DIR_DIRP_MASK)))

                    /* Selects pin direction for pin PIOm_n (bit 0 = PIOn_0, bit 1 = PIOn_1, etc.). Supported pins
                     * depends on the specific device and package. 0 = input. 1 = output.: 0x800400u */
                    | GPIO_DIR_DIRP(0x800400u));

    /* USART0_TXD connect to P0_14 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_14);

    /* USART0_RXD connect to P0_13 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_13);

    /* USART1_TXD connect to P0_4 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART1_TXD, kSWM_PortPin_P0_4);

    /* USART1_RXD connect to P0_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART1_RXD, kSWM_PortPin_P0_0);

    /* SWCLK connect to P0_3 */
    SWM_SetFixedPinSelect(SWM0, kSWM_SWCLK, true);

    /* SWDIO connect to P0_2 */
    SWM_SetFixedPinSelect(SWM0, kSWM_SWDIO, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
