/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PIO0_23 (number 1), LED
  @{ */
#define BOARD_INITPINS_LED_PERIPHERAL GPIO                    /*!<@brief Device name: GPIO */
#define BOARD_INITPINS_LED_SIGNAL PIO0                        /*!<@brief GPIO signal: PIO0 */
#define BOARD_INITPINS_LED_GPIO GPIO                          /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED_GPIO_PIN 23U                       /*!<@brief PIO0 pin index: 23 */
#define BOARD_INITPINS_LED_PORT 0U                            /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_LED_PIN 23U                            /*!<@brief 0U pin index: 23 */
#define BOARD_INITPINS_LED_CHANNEL 23                         /*!<@brief GPIO PIO0 channel: 23 */
#define BOARD_INITPINS_LED_PIN_NAME PIO0_23                   /*!<@brief Pin name */
#define BOARD_INITPINS_LED_LABEL "LED"                        /*!<@brief Label */
#define BOARD_INITPINS_LED_NAME "LED"                         /*!<@brief Identifier name */
#define BOARD_INITPINS_LED_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                              /* @} */

/*! @name PIO0_11 (number 9), DOUT
  @{ */
#define BOARD_INITPINS_DOUT_PERIPHERAL GPIO                   /*!<@brief Device name: GPIO */
#define BOARD_INITPINS_DOUT_SIGNAL PIO0                       /*!<@brief GPIO signal: PIO0 */
#define BOARD_INITPINS_DOUT_GPIO GPIO                         /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_DOUT_GPIO_PIN 11U                      /*!<@brief PIO0 pin index: 11 */
#define BOARD_INITPINS_DOUT_PORT 0U                           /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_DOUT_PIN 11U                           /*!<@brief 0U pin index: 11 */
#define BOARD_INITPINS_DOUT_CHANNEL 11                        /*!<@brief GPIO PIO0 channel: 11 */
#define BOARD_INITPINS_DOUT_PIN_NAME PIO0_11                  /*!<@brief Pin name */
#define BOARD_INITPINS_DOUT_LABEL "DOUT"                      /*!<@brief Label */
#define BOARD_INITPINS_DOUT_NAME "DOUT"                       /*!<@brief Identifier name */
#define BOARD_INITPINS_DOUT_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
                                                              /* @} */

/*! @name PIO0_10 (number 10), CLK
  @{ */
#define BOARD_INITPINS_CLK_PERIPHERAL GPIO                    /*!<@brief Device name: GPIO */
#define BOARD_INITPINS_CLK_SIGNAL PIO0                        /*!<@brief GPIO signal: PIO0 */
#define BOARD_INITPINS_CLK_GPIO GPIO                          /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_CLK_GPIO_PIN 10U                       /*!<@brief PIO0 pin index: 10 */
#define BOARD_INITPINS_CLK_PORT 0U                            /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_CLK_PIN 10U                            /*!<@brief 0U pin index: 10 */
#define BOARD_INITPINS_CLK_CHANNEL 10                         /*!<@brief GPIO PIO0 channel: 10 */
#define BOARD_INITPINS_CLK_PIN_NAME PIO0_10                   /*!<@brief Pin name */
#define BOARD_INITPINS_CLK_LABEL "CLK"                        /*!<@brief Label */
#define BOARD_INITPINS_CLK_NAME "CLK"                         /*!<@brief Identifier name */
#define BOARD_INITPINS_CLK_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
