/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Hysteresis.: Enable */
#define PIO10_HYS_ENABLE 0x01u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO10_MODE_PULL_UP 0x02u
/*!
 * @brief Hysteresis.: Enable */
#define PIO2_HYS_ENABLE 0x01u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO2_MODE_PULL_UP 0x02u

/*! @name PIO0_1 (number 12), AD_SYNC
  @{ */
#define BOARD_INITPINS_AD_SYNC_CTRL_PERIPHERAL GPIO                    /*!<@brief Device name: GPIO */
#define BOARD_INITPINS_AD_SYNC_CTRL_SIGNAL PIO0                        /*!<@brief GPIO signal: PIO0 */
#define BOARD_INITPINS_AD_SYNC_CTRL_GPIO GPIO                          /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_AD_SYNC_CTRL_GPIO_PIN 1U                        /*!<@brief PIO0 pin index: 1 */
#define BOARD_INITPINS_AD_SYNC_CTRL_PORT 0U                            /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_AD_SYNC_CTRL_PIN 1U                             /*!<@brief 0U pin index: 1 */
#define BOARD_INITPINS_AD_SYNC_CTRL_CHANNEL 1                          /*!<@brief GPIO PIO0 channel: 1 */
#define BOARD_INITPINS_AD_SYNC_CTRL_PIN_NAME PIO0_1                    /*!<@brief Pin name */
#define BOARD_INITPINS_AD_SYNC_CTRL_LABEL "AD_SYNC"                    /*!<@brief Label */
#define BOARD_INITPINS_AD_SYNC_CTRL_NAME "AD_SYNC_CTRL"                /*!<@brief Identifier name */
#define BOARD_INITPINS_AD_SYNC_CTRL_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                       /* @} */

/*! @name PIO0_23 (number 1), LED
  @{ */
#define BOARD_INITPINS_LED_CTRL_PERIPHERAL GPIO                    /*!<@brief Device name: GPIO */
#define BOARD_INITPINS_LED_CTRL_SIGNAL PIO0                        /*!<@brief GPIO signal: PIO0 */
#define BOARD_INITPINS_LED_CTRL_GPIO GPIO                          /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_LED_CTRL_GPIO_PIN 23U                       /*!<@brief PIO0 pin index: 23 */
#define BOARD_INITPINS_LED_CTRL_PORT 0U                            /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_LED_CTRL_PIN 23U                            /*!<@brief 0U pin index: 23 */
#define BOARD_INITPINS_LED_CTRL_CHANNEL 23                         /*!<@brief GPIO PIO0 channel: 23 */
#define BOARD_INITPINS_LED_CTRL_PIN_NAME PIO0_23                   /*!<@brief Pin name */
#define BOARD_INITPINS_LED_CTRL_LABEL "LED"                        /*!<@brief Label */
#define BOARD_INITPINS_LED_CTRL_NAME "LED_CTRL"                    /*!<@brief Identifier name */
#define BOARD_INITPINS_LED_CTRL_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                   /* @} */

/*! @name PIO0_17 (number 2), RWE_485
  @{ */
#define BOARD_INITPINS_RWE_485_CTRL_PERIPHERAL GPIO                    /*!<@brief Device name: GPIO */
#define BOARD_INITPINS_RWE_485_CTRL_SIGNAL PIO0                        /*!<@brief GPIO signal: PIO0 */
#define BOARD_INITPINS_RWE_485_CTRL_GPIO GPIO                          /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_RWE_485_CTRL_GPIO_PIN 17U                       /*!<@brief PIO0 pin index: 17 */
#define BOARD_INITPINS_RWE_485_CTRL_PORT 0U                            /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_RWE_485_CTRL_PIN 17U                            /*!<@brief 0U pin index: 17 */
#define BOARD_INITPINS_RWE_485_CTRL_CHANNEL 17                         /*!<@brief GPIO PIO0 channel: 17 */
#define BOARD_INITPINS_RWE_485_CTRL_PIN_NAME PIO0_17                   /*!<@brief Pin name */
#define BOARD_INITPINS_RWE_485_CTRL_LABEL "RWE_485"                    /*!<@brief Label */
#define BOARD_INITPINS_RWE_485_CTRL_NAME "RWE_485_CTRL"                /*!<@brief Identifier name */
#define BOARD_INITPINS_RWE_485_CTRL_DIRECTION kPIN_MUX_DirectionOutput /*!<@brief Direction */
                                                                       /* @} */

/*! @name PIO0_15 (number 11), AD_SPI_CS
  @{ */
#define BOARD_INITPINS_AD_SPI_CS_PERIPHERAL GPIO   /*!<@brief Device name: GPIO */
#define BOARD_INITPINS_AD_SPI_CS_SIGNAL PIO0       /*!<@brief GPIO signal: PIO0 */
#define BOARD_INITPINS_AD_SPI_CS_GPIO GPIO         /*!<@brief GPIO device name: GPIO */
#define BOARD_INITPINS_AD_SPI_CS_GPIO_PIN 15U      /*!<@brief PIO0 pin index: 15 */
#define BOARD_INITPINS_AD_SPI_CS_PORT 0U           /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_AD_SPI_CS_PIN 15U           /*!<@brief 0U pin index: 15 */
#define BOARD_INITPINS_AD_SPI_CS_CHANNEL 15        /*!<@brief GPIO PIO0 channel: 15 */
#define BOARD_INITPINS_AD_SPI_CS_PIN_NAME PIO0_15  /*!<@brief Pin name */
#define BOARD_INITPINS_AD_SPI_CS_LABEL "AD_SPI_CS" /*!<@brief Label */
#define BOARD_INITPINS_AD_SPI_CS_NAME "AD_SPI_CS"  /*!<@brief Identifier name */
                                                   /* @} */

/*! @name PIO0_11 (number 9), AD_SPI_DI
  @{ */
#define BOARD_INITPINS_AD_SPI_DI_PERIPHERAL SPI1   /*!<@brief Device name: SPI1 */
#define BOARD_INITPINS_AD_SPI_DI_SIGNAL MISO       /*!<@brief SPI1 signal: MISO */
#define BOARD_INITPINS_AD_SPI_DI_PORT 0U           /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_AD_SPI_DI_PIN 11U           /*!<@brief 0U pin index: 11 */
#define BOARD_INITPINS_AD_SPI_DI_PIN_NAME PIO0_11  /*!<@brief Pin name */
#define BOARD_INITPINS_AD_SPI_DI_LABEL "AD_SPI_DI" /*!<@brief Label */
#define BOARD_INITPINS_AD_SPI_DI_NAME "AD_SPI_DI"  /*!<@brief Identifier name */
                                                   /* @} */

/*! @name PIO0_12 (number 4), AD_SPI_DO
  @{ */
#define BOARD_INITPINS_AD_SPI_DO_PERIPHERAL SPI1   /*!<@brief Device name: SPI1 */
#define BOARD_INITPINS_AD_SPI_DO_SIGNAL MOSI       /*!<@brief SPI1 signal: MOSI */
#define BOARD_INITPINS_AD_SPI_DO_PORT 0U           /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_AD_SPI_DO_PIN 12U           /*!<@brief 0U pin index: 12 */
#define BOARD_INITPINS_AD_SPI_DO_PIN_NAME PIO0_12  /*!<@brief Pin name */
#define BOARD_INITPINS_AD_SPI_DO_LABEL "AD_SPI_DO" /*!<@brief Label */
#define BOARD_INITPINS_AD_SPI_DO_NAME "AD_SPI_DO"  /*!<@brief Identifier name */
                                                   /* @} */

/*! @name PIO0_10 (number 10), AD_SPI_CLK
  @{ */
#define BOARD_INITPINS_AD_SPI_CLK_PERIPHERAL SPI1    /*!<@brief Device name: SPI1 */
#define BOARD_INITPINS_AD_SPI_CLK_SIGNAL SCK         /*!<@brief SPI1 signal: SCK */
#define BOARD_INITPINS_AD_SPI_CLK_PORT 0U            /*!<@brief PORT device name: 0U */
#define BOARD_INITPINS_AD_SPI_CLK_PIN 10U            /*!<@brief 0U pin index: 10 */
#define BOARD_INITPINS_AD_SPI_CLK_PIN_NAME PIO0_10   /*!<@brief Pin name */
#define BOARD_INITPINS_AD_SPI_CLK_LABEL "AD_SPI_CLK" /*!<@brief Label */
#define BOARD_INITPINS_AD_SPI_CLK_NAME "AD_SPI_CLK"  /*!<@brief Identifier name */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
